name: Verify Local Development

on:
  schedule:
    - cron: '0 5 * * *' # Runs everyday at 5 AM
  workflow_dispatch:
  push:

jobs:
  verify-local-development-mode:
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-13, macos-14 ]
    runs-on: ${{ matrix.os }}
    name: Verify local development mode
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Start the local environment and verify the application startup
        run: |
          docker compose up -d

          if [[ "$RUNNER_OS" == "Windows"* ]]; then
            mvnw.cmd spring-boot:run &
          else
            ./mvnw spring-boot:run &
          fi

          timeout 180 .github/workflows/health-check.sh 8080

      - name: Stop local environment
        if: always()
        run: |
          docker compose logs
          docker compose down
