name: Verify Local Development

on:
  schedule:
    - cron: '0 5 * * *' # Runs everyday at 5 AM
  workflow_dispatch:
  push:

jobs:
  verify-local-development-mode:
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-13, macos-14 ]
    runs-on: ${{ matrix.os }}
    name: Verify local development mode
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Verify the application startup (Windows)
        if: env.RUNNER_OS == 'Windows'
        run: |
          docker compose up -d

          mvnw.cmd spring-boot:run

          health-check.ps1

      - name: Verify the application startup (macOS)
        if: env.RUNNER_OS == 'macOS'
        run: |
          brew install docker
          colima start

          docker compose up -d

          ./mvnw spring-boot:run &

          timeout 180 .github/workflows/health-check.sh 8080

      - name: Verify the application startup (Linux)
        if: env.RUNNER_OS == 'Linux'
        run: |
          docker compose up -d

          ./mvnw spring-boot:run &

          timeout 180 .github/workflows/health-check.sh 8080

      - name: Stop local environment
        if: always()
        run: |
          docker compose logs
          docker compose down
